apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-entity
  annotations:
    pagerduty.com/integration-key: 476aafac7ec74408c07a8e1df08aac48
    pagerduty.com/service-id: P4VTAK6
spec:
  type: website
  lifecycle: development
  owner: janus-authors
